### ISSUE TITLE
Latest version of nTPL on npm doesn't work with express.

### ISSUE THREAD

**Issue by mape** [indutny/nTPL#2]
Using app.set('view engine', 'nTPL'); and installing nTPL through npm I get this on page load:

TypeError: Object #<an Object> has no method 'render'
    at ServerResponse.render (/home/mape/.node_libraries/express/view.js:247:26)

**Comment by tj** [comment]
its fundamentally quite different, but the author was working on getting it to work. Compilation time is irrelevant though :p but sounds like he is going to support render(), alternatively I just added app.register() so you could tie template engines in that way http://github.com/visionmedia/express/commit/9a8166d6499110084db9279e549b9c930888e6f0

**Comment by mape** [comment]
Assumed it would work based on this commit: http://github.com/donnerjack13589/nTPL/commit/93f6598a9e36616a68f3c87d3defbd6a117cf7f8

**Comment by indutny** [comment]
I've updated nTPL on npm registry! v.0.3.5 is current stable

**Comment by indutny** [comment]
Can I close this issue?

**Comment by mape** [comment]
I'm still getting:

```
TypeError: Object #<an Object> has no method 'render'
    at ServerResponse.render (/home/mape/.node_libraries/express/view.js:247:26)
    at Object.<anonymous> (/var/www/startproject/app.js:92:6)
    at pass (/home/mape/.node_libraries/connect/middleware/router.js:65:27)
    at Object.router [as handle]  (/home/mape/.node_libraries/connect/middleware/router.js:80:10)
    at next (/home/mape/.node_libraries/connect/index.js:275:23)
    at next (/home/mape/.node_libraries/connect/index.js:277:17)
    at /home/mape/.node_libraries/connect/middleware/staticProvider.js:75:21
    at node.js:762:9
```

when using 

```
app.configure(function() {
     app.set('view engine', 'nTPL');
     app.set('views', __dirname + '/views');
});
```

And I should be using the latest version
    > npm ls nTPL installed
    nTPL@0.3.5                                    =fedor.indutny installed latest stable remote

**Comment by indutny** [comment]
I've used this code to test nTPL:
http://gist.github.com/525935

And have no errors! Try uninstalling it:
<code>npm uninstall nTPL</code>
And installing again
<code>npm install nTPL</code>

Will be waiting for your reply ;)

**Comment by indutny** [comment]
Also can you check:
<code>require("nTPL").render</code> must be function

**Comment by mape** [comment]
```
Error: EACCES, Permission denied '/home/mape/.node_libraries/nTPL.js'
    at Object.openSync (fs:150:18)
    at Object.readFileSync (fs:94:15)
    at Module._loadScriptSync (node.js:470:39)
    at Module.loadSync (node.js:341:12)
    at loadModule (node.js:286:14)
    at require (node.js:409:14)
    at ServerResponse.render (/home/mape/.node_libraries/express/view.js:243:46)
    at Object.<anonymous> (/var/www/startproject/app.js:92:6)
    at pass (/home/mape/.node_libraries/connect/middleware/router.js:65:27)
    at Object.router [as handle] (/home/mape/.node_libraries/connect/middleware/router.js:80:10)
```

and

```
TypeError: Object #<an Object> has no method 'render'
    at ServerResponse.render (/home/mape/.node_libraries/express/view.js:247:26)
    at Object.<anonymous> (/var/www/startproject/app.js:92:6)
    at pass (/home/mape/.node_libraries/connect/middleware/router.js:65:27)
    at Object.router [as handle] (/home/mape/.node_libraries/connect/middleware/router.js:80:10)
    at next (/home/mape/.node_libraries/connect/index.js:275:23)
    at next (/home/mape/.node_libraries/connect/index.js:277:17)
    at /home/mape/.node_libraries/connect/middleware/staticProvider.js:75:21
    at node.js:762:9
```

But if I run sudo node app.js it does work, never been in the position of having to run apps with sudo but apparently this requires this. Thanks for taking the time!

**Comment by indutny** [comment]
Hm...
Let me think...

**Comment by indutny** [comment]
May be you was installing nTPL using <code>sudo</code>?
<code>sudo npm install nTPL</code>

**Comment by mape** [comment]
Might be, but I've installed all my modules through sudo npm and never had to sudo node before.

**Comment by indutny** [comment]
Can you run:
<code>sudo chmod 775 /home/mape/.node_libraries/nTPL.js</code>
May be it will solve problem

**Comment by mape** [comment]
Yeah that does fix it, other people will most likely have the same issue though :)

**Comment by indutny** [comment]
I will add chmod to installer as temporary fix

**Comment by mape** [comment]
Great!

**Comment by indutny** [comment]
Please uninstall and install it using nTPL, version 0.3.6 availabel now!

**Comment by indutny** [comment]
Can we close issue now?

**Comment by mape** [comment]
The npm package seems to be broken now but yes, this issue can be closed.

```
npm ! Error: nTPL-0.3.6 preinstall: `make all`
`sh` failed with 2
at ChildProcess.<anonymous> (/home/mape/.node_libraries/.npm/npm/0.1.25/package/lib/utils/exec.js:27:18)
at ChildProcess.emit (events:33:26)
at ChildProcess.onexit (child_process:151:12)
at node.js:762:9
```

**Comment by indutny** [comment]
so we need to create new issue now ))) I need to revert npm package now, sorry.
